import { z } from "zod";

export const VIDEO_PROJECT_SCHEMA_VERSION = 1 as const;
const id = z.string().min(1).max(160);
const timing = z.object({ start: z.number().nonnegative(), end: z.number().positive(), text: z.string() }).refine(v => v.end > v.start);
const asset = z.object({ id, type: z.enum(["image","video","audio","logo","font","caption","other"]), uri: z.string().min(1), checksum: z.string().optional(), source: z.string(), provider: z.string().optional(), generationPrompt: z.string().optional(), rightsHolder: z.string().optional(), licenseStatus: z.enum(["unknown","pending","approved","rejected"]).default("unknown"), permittedUsage: z.array(z.string()).default([]), expiresAt: z.string().datetime().optional(), createdAt: z.string().datetime() });
const narration = z.object({ id, provider: z.string(), voiceId: z.string(), language: z.string(), locale: z.string(), text: z.string(), pronunciationOverrides: z.record(z.string(), z.string()).default({}), style: z.string().optional(), speed: z.number().positive().default(1), timing: z.array(timing).default([]), audioAssetId: id.optional(), estimatedCost: z.number().nonnegative().nullable().default(null), actualCost: z.number().nonnegative().nullable().default(null), requestMetadata: z.record(z.string(), z.unknown()).default({}) });
const scene = z.object({ id, order: z.number().int().nonnegative(), start: z.number().nonnegative(), duration: z.number().positive(), transitionIn: z.string().optional(), transitionOut: z.string().optional(), narrationIds: z.array(id).default([]), captionTrackIds: z.array(id).default([]), onScreenText: z.array(z.object({ text: z.string(), position: z.string().optional() })).default([]), assetIds: z.array(id).default([]), bRollAssetIds: z.array(id).default([]), backgroundAudioAssetId: id.optional(), layoutRef: z.string().optional(), providerOverrides: z.record(z.string(), z.unknown()).default({}) });

export const videoProjectSchema = z.object({
  schemaVersion: z.literal(VIDEO_PROJECT_SCHEMA_VERSION), id, revision: z.number().int().positive(), title: z.string().min(1), description: z.string().default(""), owner: z.string(), sourceBrief: z.string(), status: z.enum(["draft","active","archived"]), activeRenderId: id.optional(), approvalState: z.enum(["unreviewed","approved","rejected"]), createdAt: z.string().datetime(), updatedAt: z.string().datetime(),
  format: z.object({ kind: z.enum(["long-form","shorts","tutorial","product-demo"]), width: z.number().int().positive(), height: z.number().int().positive(), aspectRatio: z.string(), frameRate: z.number().positive(), targetDuration: z.number().positive(), outputFormat: z.enum(["mp4","mov","webm"]), language: z.string(), safeArea: z.object({ top:z.number().nonnegative(),right:z.number().nonnegative(),bottom:z.number().nonnegative(),left:z.number().nonnegative() }) }),
  scenes: z.array(scene).min(1), narration: z.array(narration).default([]), captionTracks: z.array(z.object({ id, language:z.string(), mode:z.enum(["burned-in","separate"]), style:z.record(z.string(),z.unknown()).default({}), cues:z.array(timing), corrections:z.array(z.object({ original:z.string(), corrected:z.string() })).default([]) })).default([]),
  brand: z.object({ profileId:id.optional(), templateId:z.string().optional(), logoAssetIds:z.array(id).default([]), fonts:z.array(z.string()).default([]), colors:z.array(z.string()).default([]), introRef:z.string().optional(), outroRef:z.string().optional(), lowerThirdRef:z.string().optional(), watermarkAssetId:id.optional(), layoutRefs:z.array(z.string()).default([]) }),
  assets: z.array(asset).default([]), thumbnails: z.array(z.object({ id, assetIds:z.array(id), textOverlays:z.array(z.string()), width:z.number().int().positive(), height:z.number().int().positive(), method:z.string(), approvalState:z.enum(["unreviewed","approved","rejected"]), selected:z.boolean() })).default([]),
  youtube: z.object({ title:z.string().max(100), description:z.string(), tags:z.array(z.string()), category:z.string().optional(), language:z.string(), privacy:z.enum(["private","unlisted","public"]), playlistId:z.string().optional(), captionTrackIds:z.array(id), thumbnailId:id.optional(), audience:z.enum(["made-for-kids","not-made-for-kids","unspecified"]), scheduledAt:z.string().datetime().optional() }),
  providerConfig: z.record(z.string(), z.unknown()).default({}),
}).superRefine((p, ctx) => { const ordered=[...p.scenes].sort((a,b)=>a.order-b.order); ordered.forEach((s,i)=>{ if(s.order!==i) ctx.addIssue({code:"custom",message:"Scene order must be contiguous",path:["scenes",i,"order"]}); if(i && s.start < ordered[i-1].start+ordered[i-1].duration) ctx.addIssue({code:"custom",message:"Scenes must not overlap",path:["scenes",i,"start"]}); }); });

export type VideoProject = z.infer<typeof videoProjectSchema>;
export function parseVideoProject(input: unknown) { const version=(input as {schemaVersion?:unknown})?.schemaVersion; if(typeof version==="number" && version>VIDEO_PROJECT_SCHEMA_VERSION) throw new Error(`Unsupported future VideoProject schema version: ${version}`); return videoProjectSchema.parse(input); }
